# Multiple Linear Regression 

## Importing Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Importing Data Set

In [10]:
df = pd.read_excel('Covid_data_Multiple_Linear_Regr.xlsx')
X = df.iloc[:,:-1].values
Y = df.iloc[:,-1].values
df.head()


age Body Temp  Chronic disease  Blood O2 Level in Percentage  Anti Bodies
0   10  Moderate                0                            97       127181
1   80      High                0                            92        61004
2   10       Low                0                            97       111911
3   81      High                4                            75        39010
4   12  Moderate                0                            97       110911

## Encoding categorical data

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])],remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [12]:
print(X)

[[0.0 0.0 1.0 10 0 97]
 [1.0 0.0 0.0 80 0 92]
 [0.0 1.0 0.0 10 0 97]
 [1.0 0.0 0.0 81 4 75]
 [0.0 0.0 1.0 12 0 97]
 [0.0 1.0 0.0 18 0 66]
 [0.0 0.0 1.0 13 0 93]
 [1.0 0.0 0.0 94 4 64]
 [1.0 0.0 0.0 86 2 76]
 [0.0 0.0 1.0 20 0 92]
 [0.0 0.0 1.0 15 0 94]
 [0.0 0.0 1.0 15 0 92]
 [0.0 1.0 0.0 16 0 92]
 [0.0 0.0 1.0 17 0 93]
 [0.0 0.0 1.0 18 0 93]
 [0.0 0.0 1.0 19 0 92]
 [0.0 0.0 1.0 19 0 89]
 [0.0 0.0 1.0 12 0 97]
 [0.0 0.0 1.0 20 0 93]
 [0.0 0.0 1.0 24 0 92]
 [0.0 0.0 1.0 25 0 93]
 [1.0 0.0 0.0 59 2 68]
 [1.0 0.0 0.0 63 1 66]
 [0.0 0.0 1.0 25 1 62]
 [1.0 0.0 0.0 26 0 94]
 [0.0 1.0 0.0 26 0 97]
 [0.0 0.0 1.0 28 0 99]
 [1.0 0.0 0.0 59 0 69]
 [0.0 0.0 1.0 28 0 89]
 [0.0 0.0 1.0 29 0 93]
 [0.0 0.0 1.0 48 0 93]
 [0.0 0.0 1.0 30 0 62]
 [0.0 0.0 1.0 30 0 86]
 [0.0 0.0 1.0 32 0 84]
 [0.0 0.0 1.0 34 1 90]
 [0.0 0.0 1.0 35 0 89]
 [1.0 0.0 0.0 50 2 77]
 [1.0 0.0 0.0 56 2 76]
 [1.0 0.0 0.0 56 1 77]
 [1.0 0.0 0.0 36 1 90]
 [1.0 0.0 0.0 38 2 75]
 [0.0 0.0 1.0 40 0 90]
 [1.0 0.0 0.0 40 0 92]
 [1.0 0.0 0

## Splitting into test and training set

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state=42)

## Training the Multiple Linear Regression model on the Training set

In [15]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train,Y_train)

LinearRegression()

## Predicting the Test set results

In [18]:
y_pred = reg.predict(X_test)
np.set_printoptions(precision= 3)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), Y_test.reshape(len(Y_test),1)), 1))

[[ 60698.489  59994.   ]
 [106610.635 127181.   ]
 [ 63304.777  50104.   ]
 [105389.042 110911.   ]
 [ 63167.546  62019.   ]
 [ 99229.335  97101.   ]
 [102601.651 101000.   ]
 [ 89034.772  90015.   ]
 [ 82347.886  84008.   ]
 [105089.422 100000.   ]
 [ 83253.015  75012.   ]
 [ 98911.001  98101.   ]
 [103823.243 112101.   ]
 [ 95591.144  99110.   ]
 [ 63790.34   67019.   ]
 [ 82127.038  83891.   ]
 [ 58956.779  56095.   ]
 [ 88794.054  90124.   ]
 [ 41626.827  41891.   ]
 [ 71873.925  73010.   ]
 [ 98566.795  98081.   ]]


## Visualizing results

In [ ]:
plt.plot(Y_test)
plt.plot